# Site settings
title: My Blog
email: jordan.schupbach@montana.edu
description: > # this means to ignore newlines until "baseurl:"
  My super-duper blog
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jordans1882.github.io" # the base hostname & protocol for your site
twitter_username: jordans1882
github_username:  jordans1882
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
